#ifndef RX_MAPENUM
#define RX_MAPENUM


namespace RXMapEnum
{
	namespace VersionValue
	{
		enum Version
		{
			VERSION_BETA = 57,
			VERSION_100 = 59,
			VERSION_104 = 63,
			VERSION_BROOD = 205
		};
	}
	using VersionValue::Version;

	namespace PaletteValue
	{
		enum Palette
		{
			PALETTE_NORMAL,
			PALETTE_SHADOW
		};
	}

	using PaletteValue::Palette;


	//Tileset used by the map
	namespace TileSetValue
	{
		enum TileSet
		{
			BADLANDS		= 0,
			SPACE_PLATFORM	= 1,
			INSTALLATION	= 2,
			ASHWORLD		= 3,
			JUNGLE			= 4,
			DESERT			= 5,
			ARTIC			= 6,
			TWILIGHT		= 7,
		};
	}
	using TileSetValue::TileSet;


	namespace UnitTypeValue
	{
		enum UnitType
		{
			TERRAN_MARINE=0,
			TERRAN_GHOST=1,
			TERRAN_VULTURE=2,
			TERRAN_GOLIATH=3,
			GOLIATH_TURRET=4,
			TERRAN_SIEGE_TANK_TANK_MODE=5,
			TANK_TURRET_TANK_MODE=6,
			TERRAN_SCV=7,
			TERRAN_WRAITH=8,
			TERRAN_SCIENCE_VESSEL=9,
			GUI_MONTANG_FIREBAT=10,
			TERRAN_DROPSHIP=11,
			TERRAN_BATTLECRUISER=12,
			VULTURE_SPIDER_MINE=13,
			NUCLEAR_MISSILE=14,
			TERRAN_CIVILIAN=15,
			SARAH_KERRIGAN_GHOST=16,
			ALAN_SCHEZAR_GOLIATH=17,
			ALAN_SCHEZAR_TURRET=18,
			JIM_RAYNOR_VULTURE=19,
			JIM_RAYNOR_MARINE=20,
			TOM_KAZANSKY_WRAITH=21,
			MAGELLAN_SCIENCE_VESSEL=22,
			EDMUND_DUKE_SIEGE_TANK=23,
			EDMUND_DUKE_TURRET=24,
			EDMUND_DUKE_SIEGE_MODE=25,
			EDMUND_DUKE_TURRET2=26,
			ARCTURUS_MENGSK_BATTLECRUISER=27,
			HYPERION_BATTLECRUISER=28,
			NORAD_II_BATTLECRUISER=29,
			TERRAN_SIEGE_TANK=30,
			TANK_TURRET=31,
			FIREBAT=32,
			SCANNER_SWEEP=33,
			TERRAN_MEDIC=34,
			ZERG_LARVA=35,
			ZERG_EGG=36,
			ZERG_ZERGLING=37,
			ZERG_HYDRALISK=38,
			ZERG_ULTRALISK=39,
			ZERG_BROODLING=40,
			ZERG_DRONE=41,
			ZERG_OVERLORD=42,
			ZERG_MUTALISK=43,
			ZERG_GUARDIAN=44,
			ZERG_QUEEN=45,
			ZERG_DEFILER=46,
			ZERG_SCOURGE=47,
			TORRARSQUE_ULTRALISK=48,
			MATRIARCH_QUEEN=49,
			INFESTED_TERRAN=50,
			INFESTED_KERRIGAN=51,
			UNCLEAN_ONE_DEFILER=52,
			HUNTER_KILLER_HYDRALISK=53,
			DEVOURING_ONE_ZERGLING=54,
			KUKULZA_MUTALISK=55,
			KUKULZA_GUARDIAN=56,
			YGGDRASILL_OVERLORD=57,
			TERRAN_VALKYRIE_FRIGATE=58,
			MUTALISK_GUARDIAN_COCOON=59,
			PROTOSS_CORSAIR=60,
			PROTOSS_DARK_TEMPLARUNIT=61,
			ZERG_DEVOURER=62,
			PROTOSS_DARK_ARCHON=63,
			PROTOSS_PROBE=64,
			PROTOSS_ZEALOT=65,
			PROTOSS_DRAGOON=66,
			PROTOSS_HIGH_TEMPLAR=67,
			PROTOSS_ARCHON=68,
			PROTOSS_SHUTTLE=69,
			PROTOSS_SCOUT=70,
			PROTOSS_ARBITER=71,
			PROTOSS_CARRIER=72,
			PROTOSS_INTERCEPTOR=73,
			DARK_TEMPLARHERO=74,
			ZERATUL_DARK_TEMPLAR=75,
			TASSADAR_ZERATUL_ARCHON=76,
			FENIX_ZEALOT=77,
			FENIX_DRAGOON=78,
			TASSADAR_TEMPLAR=79,
			MOJO_SCOUT=80,
			WARBRINGER_REAVER=81,
			GANTRITHOR_CARRIER=82,
			PROTOSS_REAVER=83,
			PROTOSS_OBSERVER=84,
			PROTOSS_SCARAB=85,
			DANIMOTH_ARBITER=86,
			ALDARIS_TEMPLAR=87,
			ARTANIS_SCOUT=88,
			RHYNADON=89,
			BENGALAAS=90,

			SCANTID=93,
			KAKARU=94,
			RAGNASAUR=95,
			URSADON=96,
			LURKER_EGG=97,
			RASZAGAL=98,
			SAMIR_DURAN_GHOST=99,
			ALEXEI_STUKOV_GHOST=100,
			MAP_REVEALER=101,
			GERARD_DUGALLE=102,
			ZERG_LURKER=103,
			INFESTED_DURAN=104,
			DISRUPTION_WEB=105,
			TERRAN_COMMAND_CENTER=106,
			TERRAN_COMSAT_STATION=107,
			TERRAN_NUCLEAR_SILO=108,
			TERRAN_SUPPLY_DEPOT=109,
			TERRAN_REFINERY=110,
			TERRAN_BARRACKS=111,
			TERRAN_ACADEMY=112,
			TERRAN_FACTORY=113,
			TERRAN_STARPORT=114,
			TERRAN_CONTROL_TOWER=115,
			TERRAN_SCIENCE_FACILITY=116,
			TERRAN_COVERT_OPS=117,
			TERRAN_PHYSICS_LAB=118,

			TERRAN_MACHINE_SHOP=120,

			TERRAN_ENGINEERING_BAY=122,
			TERRAN_ARMORY=123,
			TERRAN_MISSILE_TURRET=124,
			TERRAN_BUNKER=125,
			NORAD_II=126,
			ION_CANNON=127,
			URAJ_CRYSTAL=128,
			KHALIS_CRYSTAL=129,
			INFESTED_COMMAND_CENTER=130,
			ZERG_HATCHERY=131,
			ZERG_LAIR=132,
			ZERG_HIVE=133,
			ZERG_NYDUS_CANAL=134,
			ZERG_HYDRALISK_DEN=135,
			ZERG_DEFILER_MOUND=136,
			ZERG_GREATER_SPIRE=137,
			ZERG_QUEENS_NEST=138,
			ZERG_EVOLUTION_CHAMBER=139,
			ZERG_ULTRALISK_CAVERN=140,
			ZERG_SPIRE=141,
			ZERG_SPAWNING_POOL=142,
			ZERG_CREEP_COLONY=143,
			ZERG_SPORE_COLONY=144,

			ZERG_SUNKEN_COLONY=146,
			ZERG_OVERMIND_WITH_SHELL=147,
			ZERG_OVERMIND=148,
			ZERG_EXTRACTOR=149,
			MATURE_CHRYSALIS=150,
			ZERG_CEREBRATE=151,
			ZERG_CEREBRATE_DAGGOTH=152,

			PROTOSS_NEXUS=154,
			PROTOSS_ROBOTICS_FACILITY=155,
			PROTOSS_PYLON=156,
			PROTOSS_ASSIMILATOR=157,

			PROTOSS_OBSERVATORY=159,
			PROTOSS_GATEWAY=160,

			PROTOSS_PHOTON_CANNON=162,
			PROTOSS_CITADEL_OF_ADUN=163,
			PROTOSS_CYBERNETICS_CORE=164,
			PROTOSS_TEMPLAR_ARCHIVES=165,
			PROTOSS_FORGE=166,
			PROTOSS_STARGATE=167,
			STASIS_CELL_PRISON=168,
			PROTOSS_FLEET_BEACON=169,
			PROTOSS_ARBITER_TRIBUNAL=170,
			PROTOSS_ROBOTICS_SUPPORT_BAY=171,
			PROTOSS_SHIELD_BATTERY=172,
			KHAYDARIN_CRYSTAL_FORMATION=173,
			PROTOSS_TEMPLE=174,
			XEL_NAGA_TEMPLE=175,
			MINERAL_FIELD_TYPE_1=176,
			MINERAL_FIELD_TYPE_2=177,
			MINERAL_FIELD_TYPE_3=178,
			CAVE=179,
			CAVE_IN=180,
			CANTINA=181,
			MINING_PLATFORM=182,
			INDEPENDANT_COMMAND_CENTER=183,
			INDEPENDANT_STARPORT=184,
			INDEPENDANT_JUMP_GATE=185,
			RUINS=186,
			KYADARIN_CRYSTAL_FORMATION=187,
			VESPENE_GEYSER=188,
			WARP_GATE=189,
			PSI_DISRUPTOR=190,
			ZERG_MARKER=191,
			TERRAN_MARKER=192,
			PROTOSS_MARKER=193,
			ZERG_BEACON=194,
			TERRAN_BEACON=195,
			PROTOSS_BEACON=196,
			ZERG_FLAG_BEACON=197,
			TERRAN_FLAG_BEACON=198,
			PROTOSS_FLAG_BEACON=199,
			POWER_GENERATOR=200,
			OVERMIND_COCOON=201,
			DARK_SWARM=202,
			FLOOR_MISSILE_TRAP=203,
			FLOOR_HATCH=204,
			LEFT_UPPER_LEVEL_DOOR=205,
			RIGHT_UPPER_LEVEL_DOOR=206,
			LEFT_PIT_DOOR=207,
			RIGHT_PIT_DOOR=208,
			FLOOR_GUN_TRAP=209,
			LEFT_WALL_MISSILE_TRAP=210,
			LEFT_WALL_FLAME_TRAP=211,
			RIGHT_WALL_MISSILE_TRAP=212,
			RIGHT_WALL_FLAME_TRAP=213,
			START_LOCATION=214,
			FLAG=215,
			YOUNG_CHRYSALIS=216,
			PSI_EMITTER=217,
			DATA_DISC=218,
			KHAYDARIN_CRYSTAL=219,
			MINERAL_CLUSTER_TYPE_1=220,
			MINERAL_CLUSTER_TYPE_2=221,
			PROTOSS_VESPENE_GAS_ORB_TYPE_1=222,
			PROTOSS_VESPENE_GAS_ORB_TYPE_2=223,
			ZERG_VESPENE_GAS_SAC_TYPE_1=224,
			ZERG_VESPENE_GAS_SAC_TYPE_2=225,
			TERRAN_VESPENE_GAS_TANK_TYPE_1=226,
			TERRAN_VESPENE_GAS_TANK_TYPE_2=227
		};
	}

	using UnitTypeValue::UnitType;
};


#ifdef __GNUC__
#include <misc/RXHashmap.h>
namespace RX_HASHNAMESPACE
{
	template<> 
	struct hash<RXMapEnum::TileSetValue::TileSet> 
	{
		size_t operator()(const RXMapEnum::TileSetValue::TileSet & x) const 
		{
			return (size_t)x;
		}
	};

	template<> 
	struct hash<RXMapEnum::UnitType> 
	{
		size_t operator()(const RXMapEnum::UnitType & x) const 
		{
			return (size_t)x;
		}
	};
}

#endif


#endif



